ESKF:
  process_vel_noise: 0.1
  process_rot_noise: 0.1
  process_ba_noise: 1.0e-7
  process_bg_noise: 1.0e-7
  measurement_pos_noise: 1.0e-4
  measurement_rot_noise: 1.0e-4

FrontEnd:
  lidar_buffer_upper_capacity: 100
  imu_buffer_upper_capacity: 2000
  gps_buffer_upper_capacity: 2000

  lidar_buffer_lower_capacity: 30
  imu_buffer_lower_capacity: 200
  gps_buffer_lower_capacity: 200

  lio_dir_path: "./LIO_results"

GeoConverter:
  a: 6378137.0
  f: 0.0033528106647474805   
  b: 6356752.314245          
  e2: 0.00669437999014       

LidarOdometry:
  voxel_resolution: 0.8
  voxel_resolution_x: 0.8
  voxel_resolution_y: 0.8
  voxel_resolution_z: 0.8
  ndt_resolution: 3.0
  scan_matching_use_gicp_fine_alignment: true
  scan_matching_gicp_max_correspondence_dist: 0.5
  scan_matching_gicp_max_iter: 10
  scan_matching_gicp_transform_epsilon: 1.0e-2
  scan_matching_gicp_fitness_epsilon: 1.0e-2
  lidar_x_range: 60.0
  lidar_y_range: 40.0
  lidar_z_range: 5.0
  reject_large_pose_jump: true
  max_pose_jump_translation: 2.0
  max_pose_jump_rotation_deg: 5.0

DataLoader:
  remove_groud: true
  kitti_groud_height: -1.0
  ros_bag_path: "/root/ros2_ws/2011_10_03_drive_0027_bag"

General:
  map_voxel_resolution: 0.45
  map_voxel_resolution_x: 0.45
  map_voxel_resolution_y: 0.45
  map_voxel_resolution_z: 0.45
  num_pts_threshold_for_viz: 20
  save_lo_frame: false
  save_lio_frame: true
  filter_saved_cloud: true
  using_LIO_only: false
  save_loop_closure_debug_info: true

LoopClosure:
  loop_closure_search_radius: 15.0
  loop_closure_min_keyframe_gap: 10
  top_k_loop_closure_candidates: 5
  loop_closure_fitness_score_threshold: 50.0
  loop_closure_gicp_fitness_score_threshold: 5.0
  skip_count_for_loop_closure_detection: 10

Optimizer:
  gps_edge_weight: 0.005
  gps_relative_edge_weight: 0.00001
  lio_edge_weight: 1000.0
  loop_closure_edge_weight: 300.0
  local_optimization_widnow_size: 7
  min_keyframe_num_for_optimization: 5
  local_iterations: 10
  global_iterations: 80