#!/usr/bin/env python3

import argparse
import json
import struct
from pathlib import Path
from typing import Dict, Iterator, List, Tuple

import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy
from sensor_msgs.msg import PointCloud2, PointField
from sensor_msgs_py import point_cloud2
from std_msgs.msg import Header


DEFAULT_METADATA_PATH = Path("/root/ros2_ws/build/offline_lidar_slam/LIO_results/key_frames.jsonl")
FRAME_A_COLOR = np.array([242, 89, 38], dtype=np.uint8)
FRAME_B_COLOR = np.array([26, 140, 242], dtype=np.uint8)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Publish two keyframe point clouds to RViz2 using saved paths and recorded poses."
    )
    parser.add_argument("frame_a", type=int, help="First keyframe ID to load.")
    parser.add_argument("frame_b", type=int, help="Second keyframe ID to load.")
    parser.add_argument(
        "--metadata-path",
        type=Path,
        default=DEFAULT_METADATA_PATH,
        help=f"Path to key_frames.jsonl generated by SlamProcess. Default: {DEFAULT_METADATA_PATH}",
    )
    parser.add_argument(
        "--pose-field",
        choices=("optimized_pose", "lio_pose"),
        default="optimized_pose",
        help="Which pose field from the metadata to apply to the saved keyframe cloud.",
    )
    parser.add_argument(
        "--topic",
        default="/ply_cloud",
        help="PointCloud2 topic to publish for RViz2.",
    )
    parser.add_argument(
        "--frame-id",
        default="map",
        help="TF frame_id used in the published PointCloud2 message.",
    )
    parser.add_argument(
        "--publish-rate",
        type=float,
        default=1.0,
        help="Publish rate in Hz.",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=250000,
        help="Maximum total points after uniform downsampling. Non-positive disables downsampling.",
    )
    return parser.parse_args()


def iter_json_objects(text: str) -> Iterator[dict]:
    brace_depth = 0
    object_start = None
    for index, char in enumerate(text):
        if char == "{":
            if brace_depth == 0:
                object_start = index
            brace_depth += 1
        elif char == "}":
            brace_depth -= 1
            if brace_depth == 0 and object_start is not None:
                yield json.loads(text[object_start:index + 1])
                object_start = None


def load_keyframe_index(metadata_path: Path) -> Dict[int, dict]:
    if not metadata_path.is_file():
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    text = metadata_path.read_text(encoding="utf-8")
    records = {}
    for record in iter_json_objects(text):
        records[int(record["key_frame_id"])] = record
    if not records:
        raise ValueError(f"No keyframe records found in metadata file: {metadata_path}")
    return records


def resolve_cloud_path(metadata_path: Path, saved_frame_path: str) -> Path:
    saved_path = Path(saved_frame_path)
    if saved_path.is_absolute():
        return saved_path

    candidates = [
        (metadata_path.parent / saved_path).resolve(),
        (metadata_path.parent.parent / saved_path).resolve(),
        saved_path.resolve(),
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate

    return candidates[0]


def read_ascii_ply_vertices(ply_path: Path) -> np.ndarray:
    vertex_count = None
    header_ended = False
    points: List[Tuple[float, float, float]] = []

    with ply_path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not header_ended:
                if line.startswith("element vertex"):
                    vertex_count = int(line.split()[-1])
                elif line == "end_header":
                    header_ended = True
                continue

            if not line:
                continue

            xyz = line.split()
            if len(xyz) < 3:
                continue

            try:
                points.append((float(xyz[0]), float(xyz[1]), float(xyz[2])))
            except ValueError:
                continue

            if vertex_count is not None and len(points) >= vertex_count:
                break

    if vertex_count is None:
        raise ValueError(f"Could not find vertex count in PLY header: {ply_path}")
    if not points:
        raise ValueError(f"No vertices found in PLY file: {ply_path}")

    return np.asarray(points, dtype=np.float32)


def uniform_downsample(points: np.ndarray, max_points: int) -> np.ndarray:
    if max_points <= 0 or points.shape[0] <= max_points:
        return points

    stride = int(np.ceil(points.shape[0] / max_points))
    return points[::stride]


def quaternion_xyzw_to_rotation_matrix(quaternion_xyzw: List[float]) -> np.ndarray:
    x, y, z, w = quaternion_xyzw
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z

    return np.asarray([
        [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy)],
        [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
        [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy)],
    ], dtype=np.float32)


def transform_points(points: np.ndarray, pose_record: dict) -> np.ndarray:
    rotation = quaternion_xyzw_to_rotation_matrix(pose_record["quaternion_xyzw"])
    translation = np.asarray(pose_record["translation"], dtype=np.float32)
    return points @ rotation.T + translation


def make_rgb_uint32(color: np.ndarray) -> int:
    return struct.unpack("I", struct.pack("BBBB", int(color[2]), int(color[1]), int(color[0]), 0))[0]


def colored_cloud(points: np.ndarray, color: np.ndarray) -> np.ndarray:
    rgb = np.full((points.shape[0], 1), make_rgb_uint32(color), dtype=np.uint32)
    xyz = points.astype(np.float32, copy=False)
    return np.hstack((xyz, rgb.view(np.float32)))


def load_transformed_keyframes(
    metadata_path: Path,
    frame_a: int,
    frame_b: int,
    pose_field: str,
    max_points: int,
) -> np.ndarray:
    keyframe_index = load_keyframe_index(metadata_path)
    clouds = []

    for frame_id, color in ((frame_a, FRAME_A_COLOR), (frame_b, FRAME_B_COLOR)):
        if frame_id not in keyframe_index:
            raise KeyError(f"Keyframe ID {frame_id} not found in metadata file {metadata_path}")

        record = keyframe_index[frame_id]
        ply_path = resolve_cloud_path(metadata_path, record["saved_frame_path"])
        if not ply_path.is_file():
            raise FileNotFoundError(f"Saved keyframe cloud not found for keyframe {frame_id}: {ply_path}")

        points = read_ascii_ply_vertices(ply_path)
        points = transform_points(points, record[pose_field])
        points = uniform_downsample(points, max_points // 2 if max_points > 0 else max_points)
        clouds.append(colored_cloud(points, color))

        print(
            f"Loaded keyframe {frame_id:06d} from {ply_path} "
            f"using {pose_field} with {points.shape[0]} transformed points"
        )

    return np.vstack(clouds)


class TwoFramePublisher(Node):
    def __init__(self, args: argparse.Namespace, cloud_points: np.ndarray):
        super().__init__("two_frame_cloud_publisher")
        qos = QoSProfile(
            depth=1,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
        )
        self.publisher = self.create_publisher(PointCloud2, args.topic, qos)
        self.frame_id = args.frame_id
        self.cloud_points = cloud_points.tolist()
        self.fields = [
            PointField(name="x", offset=0, datatype=PointField.FLOAT32, count=1),
            PointField(name="y", offset=4, datatype=PointField.FLOAT32, count=1),
            PointField(name="z", offset=8, datatype=PointField.FLOAT32, count=1),
            PointField(name="rgb", offset=12, datatype=PointField.FLOAT32, count=1),
        ]
        period = 1.0 / max(args.publish_rate, 1e-6)
        self.timer = self.create_timer(period, self.publish_cloud)
        self.publish_cloud()

    def publish_cloud(self) -> None:
        header = Header()
        header.stamp = self.get_clock().now().to_msg()
        header.frame_id = self.frame_id
        msg = point_cloud2.create_cloud(header, self.fields, self.cloud_points)
        self.publisher.publish(msg)


def main() -> int:
    cli_args = parse_args()
    cloud_points = load_transformed_keyframes(
        cli_args.metadata_path,
        cli_args.frame_a,
        cli_args.frame_b,
        cli_args.pose_field,
        cli_args.max_points,
    )

    print(
        f"Publishing keyframes {cli_args.frame_a:06d} and {cli_args.frame_b:06d} "
        f"to {cli_args.topic} with {cloud_points.shape[0]} transformed colored points"
    )
    print("In RViz2, set the PointCloud2 display Color Transformer to RGB8.")

    rclpy.init()
    node = TwoFramePublisher(cli_args, cloud_points)
    try:
        rclpy.spin(node)
    finally:
        node.destroy_node()
        rclpy.shutdown()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
