#!/usr/bin/env python3
"""Visualize a batch of colored PLY clouds in a common frame with Open3D.

The script loads keyframe pose information from key_frames.jsonl, reads the
colored PLY files produced by project_keyframes_to_image.py, transforms each
cloud into the requested reference frame, voxel-aggregates position and RGB,
and then renders the merged cloud in Open3D.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

try:
    import open3d as o3d
except ImportError as exc:  # pragma: no cover - runtime dependency guard
    raise SystemExit(
        "open3d is required. Install it with: pip install open3d"
    ) from exc


DEFAULT_KEYFRAMES_PATH = Path("/root/ros2_ws/build/offline_lidar_slam/key_frames.jsonl")
DEFAULT_CLOUD_DIR = Path("/root/ros2_ws/build/offline_lidar_slam/projection_check")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize a batch of colored PLY clouds with pose alignment and voxel RGB aggregation."
    )
    parser.add_argument(
        "--keyframes-path",
        type=Path,
        default=DEFAULT_KEYFRAMES_PATH,
        help="Path to key_frames.jsonl generated by the SLAM pipeline.",
    )
    parser.add_argument(
        "--cloud-dir",
        type=Path,
        default=DEFAULT_CLOUD_DIR,
        help="Directory containing *_colored.ply files.",
    )
    parser.add_argument(
        "--keyframe-ids",
        type=int,
        nargs="*",
        default=None,
        help="Optional keyframe IDs to visualize. If omitted, all matching clouds are used.",
    )
    parser.add_argument(
        "--pose-field",
        choices=("optimized_pose", "lio_pose"),
        default="optimized_pose",
        help="Pose field to use from key_frames.jsonl.",
    )
    parser.add_argument(
        "--voxel-size",
        type=float,
        default=0.10,
        help="Voxel size in meters used to aggregate XYZ and RGB.",
    )
    parser.add_argument(
        "--point-size",
        type=float,
        default=2.0,
        help="Open3D point size used during visualization.",
    )
    parser.add_argument(
        "--window-name",
        type=str,
        default="Batch Colored PLY Viewer",
        help="Open3D window title.",
    )
    parser.add_argument(
        "--background",
        choices=("dark", "light", "gray", "white", "black"),
        default="dark",
        help="Viewer background preset.",
    )
    parser.add_argument(
        "--max-clouds",
        type=int,
        default=0,
        help="Optional limit on how many clouds to load. 0 means no limit.",
    )
    parser.add_argument(
        "--no-window",
        action="store_true",
        help="Do not open an Open3D window; save a preview image instead.",
    )
    parser.add_argument(
        "--preview-path",
        type=Path,
        default=None,
        help="Path to save a 2D preview image when --no-window is set or the environment is headless.",
    )
    parser.add_argument(
        "--save-merged-ply",
        type=Path,
        default=None,
        help="Optional path to save the voxelized merged colored cloud as ASCII PLY.",
    )
    return parser.parse_args()


def parse_keyframe_records(path: Path) -> Dict[int, dict]:
    if not path.is_file():
        raise FileNotFoundError(f"Keyframe jsonl not found: {path}")

    text = path.read_text(encoding="utf-8")
    records: Dict[int, dict] = {}
    depth = 0
    start_idx: Optional[int] = None
    in_string = False
    escaped = False

    for idx, ch in enumerate(text):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
            continue

        if ch == "{":
            if depth == 0:
                start_idx = idx
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start_idx is not None:
                record = json.loads(text[start_idx : idx + 1])
                records[int(record["key_frame_id"])] = record
                start_idx = None

    if not records:
        raise ValueError(f"No keyframe records found in {path}")
    return records


def read_colored_ascii_ply(ply_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    if not ply_path.is_file():
        raise FileNotFoundError(f"PLY file not found: {ply_path}")

    vertex_count = None
    header_ended = False
    points: List[Tuple[float, float, float]] = []
    colors: List[Tuple[float, float, float]] = []

    with ply_path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not header_ended:
                if line.startswith("element vertex"):
                    vertex_count = int(line.split()[-1])
                elif line == "end_header":
                    header_ended = True
                continue

            if not line:
                continue

            parts = line.split()
            if len(parts) < 6:
                continue

            try:
                x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
                r, g, b = int(parts[3]), int(parts[4]), int(parts[5])
            except ValueError:
                continue

            points.append((x, y, z))
            colors.append((r / 255.0, g / 255.0, b / 255.0))

            if vertex_count is not None and len(points) >= vertex_count:
                break

    if not points:
        raise ValueError(f"No colored vertices found in PLY file: {ply_path}")

    return np.asarray(points, dtype=np.float32), np.asarray(colors, dtype=np.float32)


def quaternion_xyzw_to_rotation_matrix(quaternion_xyzw: Sequence[float]) -> np.ndarray:
    x, y, z, w = quaternion_xyzw
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z

    return np.asarray([
        [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy)],
        [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
        [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy)],
    ], dtype=np.float32)


def transform_points(points: np.ndarray, pose_record: dict) -> np.ndarray:
    rotation = quaternion_xyzw_to_rotation_matrix(pose_record["quaternion_xyzw"])
    translation = np.asarray(pose_record["translation"], dtype=np.float32)
    return points @ rotation.T + translation


def background_rgb(preset: str) -> Tuple[float, float, float]:
    mapping = {
        "dark": (0.08, 0.08, 0.08),
        "light": (0.92, 0.92, 0.92),
        "gray": (0.5, 0.5, 0.5),
        "white": (1.0, 1.0, 1.0),
        "black": (0.0, 0.0, 0.0),
    }
    return mapping[preset]


def write_ascii_ply_xyzrgb(ply_path: Path, points_xyz: np.ndarray, rgb: np.ndarray) -> None:
    if points_xyz.shape[0] != rgb.shape[0]:
        raise ValueError("points_xyz and rgb must have the same number of rows")

    ply_path.parent.mkdir(parents=True, exist_ok=True)
    with ply_path.open("w", encoding="utf-8") as f:
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"element vertex {points_xyz.shape[0]}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        f.write("property uchar red\n")
        f.write("property uchar green\n")
        f.write("property uchar blue\n")
        f.write("end_header\n")
        for i in range(points_xyz.shape[0]):
            x, y, z = points_xyz[i]
            r, g, b = rgb[i]
            f.write(f"{x:.6f} {y:.6f} {z:.6f} {int(r)} {int(g)} {int(b)}\n")


def make_preview_image(points: np.ndarray, colors: np.ndarray, background: str) -> np.ndarray:
    width = 2400
    height = 1200
    canvas = np.zeros((height, width, 3), dtype=np.uint8)
    bg = np.asarray(background_rgb(background), dtype=np.float32)
    canvas[:] = np.round(bg * 255.0).astype(np.uint8)

    if points.shape[0] == 0:
        return canvas

    def draw_view(view_points: np.ndarray, view_colors: np.ndarray, x_idx: int, y_idx: int, x0: int, y0: int, w: int, h: int) -> None:
        xs = view_points[:, x_idx]
        ys = view_points[:, y_idx]
        if xs.size == 0:
            return
        x_min, x_max = float(np.min(xs)), float(np.max(xs))
        y_min, y_max = float(np.min(ys)), float(np.max(ys))
        x_span = max(x_max - x_min, 1e-6)
        y_span = max(y_max - y_min, 1e-6)

        px = np.clip(((xs - x_min) / x_span) * (w - 1), 0, w - 1).astype(np.int32)
        py = np.clip((1.0 - (ys - y_min) / y_span) * (h - 1), 0, h - 1).astype(np.int32)

        # Keep the closest point per pixel in the chosen view using the omitted axis as depth.
        depth_axis = 2 if x_idx == 0 and y_idx == 1 else 1
        depth = view_points[:, depth_axis]
        flat = py * w + px
        order = np.argsort(depth)
        flat_sorted = flat[order]
        keep_first = np.ones(flat_sorted.shape[0], dtype=bool)
        keep_first[1:] = flat_sorted[1:] != flat_sorted[:-1]
        keep_indices = order[keep_first]
        px = px[keep_indices]
        py = py[keep_indices]
        view_colors = view_colors[keep_indices]

        canvas[y0 : y0 + h, x0 : x0 + w, :] = canvas[y0 : y0 + h, x0 : x0 + w, :]
        for i in range(px.shape[0]):
            canvas[y0 + py[i], x0 + px[i], :] = np.clip(np.round(view_colors[i] * 255.0), 0, 255).astype(np.uint8)

    # Left: top-down XY, Right: side XZ.
    draw_view(points, colors, 0, 1, 40, 40, 1100, 1120)
    draw_view(points, colors, 0, 2, 1260, 40, 1100, 1120)
    return canvas


def voxel_aggregate(points: np.ndarray, colors: np.ndarray, voxel_size: float) -> Tuple[np.ndarray, np.ndarray]:
    if voxel_size <= 0.0:
        return points, colors

    voxel_index = np.floor(points / voxel_size).astype(np.int64)
    unique_voxels, inverse = np.unique(voxel_index, axis=0, return_inverse=True)

    counts = np.bincount(inverse)
    xyz_sum = np.zeros((unique_voxels.shape[0], 3), dtype=np.float64)
    rgb_sum = np.zeros((unique_voxels.shape[0], 3), dtype=np.float64)

    for axis in range(3):
        xyz_sum[:, axis] = np.bincount(inverse, weights=points[:, axis], minlength=unique_voxels.shape[0])
        rgb_sum[:, axis] = np.bincount(inverse, weights=colors[:, axis], minlength=unique_voxels.shape[0])

    xyz_mean = xyz_sum / counts[:, None]
    rgb_mean = np.clip(rgb_sum / counts[:, None], 0.0, 1.0)
    return xyz_mean.astype(np.float32), rgb_mean.astype(np.float32)


def build_merged_cloud(
    records: Dict[int, dict],
    cloud_dir: Path,
    keyframe_ids: Optional[Sequence[int]],
    pose_field: str,
    max_clouds: int,
) -> Tuple[np.ndarray, np.ndarray, int]:
    if not cloud_dir.is_dir():
        raise FileNotFoundError(f"Cloud directory not found: {cloud_dir}")

    ids = list(keyframe_ids) if keyframe_ids is not None else sorted(records.keys())
    if max_clouds > 0:
        ids = ids[:max_clouds]

    merged_points: List[np.ndarray] = []
    merged_colors: List[np.ndarray] = []
    loaded = 0

    for keyframe_id in ids:
        if keyframe_id not in records:
            print(f"[WARN] key_frame_id={keyframe_id} not found in keyframe metadata; skipping")
            continue

        record = records[keyframe_id]
        candidates = sorted(cloud_dir.glob(f"kf_{keyframe_id:06d}_img_*_colored.ply"))
        if not candidates:
            print(f"[WARN] missing colored cloud for key_frame_id={keyframe_id:06d} in {cloud_dir}")
            continue

        ply_path = candidates[0]

        points, colors = read_colored_ascii_ply(ply_path)
        points = transform_points(points, record[pose_field])
        merged_points.append(points)
        merged_colors.append(colors)
        loaded += 1
        print(f"[LOAD] key_frame_id={keyframe_id:06d} points={points.shape[0]} path={ply_path}")

    if not merged_points:
        raise ValueError("No clouds were loaded. Check keyframe IDs, cloud directory, and file naming.")

    return np.vstack(merged_points), np.vstack(merged_colors), loaded


def main() -> int:
    args = parse_args()
    records = parse_keyframe_records(args.keyframes_path)

    merged_points, merged_colors, loaded_clouds = build_merged_cloud(
        records=records,
        cloud_dir=args.cloud_dir,
        keyframe_ids=args.keyframe_ids,
        pose_field=args.pose_field,
        max_clouds=args.max_clouds,
    )

    voxel_points, voxel_colors = voxel_aggregate(merged_points, merged_colors, args.voxel_size)

    if args.save_merged_ply is not None:
        write_ascii_ply_xyzrgb(args.save_merged_ply, voxel_points, np.clip(np.round(voxel_colors * 255.0), 0, 255).astype(np.uint8))
        print(f"[SAVE] merged voxelized cloud written to {args.save_merged_ply}")

    if args.no_window:
        preview_path = args.preview_path or Path("/tmp/batch_colored_preview.png")
        preview = make_preview_image(voxel_points, voxel_colors, args.background)
        preview_path.parent.mkdir(parents=True, exist_ok=True)
        from PIL import Image

        Image.fromarray(preview).save(preview_path)
        print(f"[HEADLESS] saved preview image to {preview_path}")
        print("[PREVIEW] interactive Open3D window skipped because --no-window was set")
        return 0

    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(voxel_points)
    cloud.colors = o3d.utility.Vector3dVector(voxel_colors)

    print(
        f"Loaded {voxel_points.shape[0]} voxelized points from {loaded_clouds} clouds "
        f"using pose_field={args.pose_field} voxel_size={args.voxel_size}"
    )

    vis = o3d.visualization.Visualizer()
    vis.create_window(window_name=args.window_name)
    vis.add_geometry(cloud)
    render_option = vis.get_render_option()
    if render_option is not None:
        render_option.point_size = float(args.point_size)
        render_option.background_color = np.asarray(background_rgb(args.background), dtype=np.float32)

    vis.run()
    vis.destroy_window()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
